/**
 * Self-contained HTML report — one file, inline CSS, anchor links per rule.
 * Intended for CI artifact uploads (GitHub Actions `upload-artifact`, S3, etc.)
 * where a link to a rendered report beats a JSON dump. No external assets;
 * opens in any browser offline.
 */

import type { Issue, RunReport } from "../types.js";

export function formatHtml(report: RunReport): string {
  const total = report.errorCount + report.warningCount + report.infoCount;
  const title = total === 0
    ? `mcpcheck: clean (${report.files.length} file${report.files.length === 1 ? "" : "s"})`
    : `mcpcheck: ${report.errorCount} error${report.errorCount === 1 ? "" : "s"}, ${report.warningCount} warning${report.warningCount === 1 ? "" : "s"}`;

  const fileSections = report.files
    .filter((f) => f.issues.length > 0)
    .map((f) => renderFileSection(f.file, f.issues))
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>${esc(title)}</title>
<style>
  :root { color-scheme: light dark;
    --bg:#fff; --fg:#111; --muted:#666; --border:#ddd;
    --err:#b91c1c; --warn:#b45309; --info:#1d4ed8; --ok:#15803d;
    --mono: ui-monospace, "SF Mono", Menlo, Consolas, monospace;
  }
  @media (prefers-color-scheme: dark) {
    :root { --bg:#0d1017; --fg:#e6e9ef; --muted:#8b93a4; --border:#242a38;
      --err:#f87171; --warn:#fbbf24; --info:#60a5fa; --ok:#4ade80; }
  }
  body { margin:0; background:var(--bg); color:var(--fg);
    font:14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
  header { padding:1.25rem 1.5rem; border-bottom:1px solid var(--border); }
  h1 { margin:0; font-size:1.25rem; }
  .summary { color:var(--muted); margin-top:.25rem; font-size:.9rem; }
  main { padding:1rem 1.5rem; max-width:1100px; margin:0 auto; }
  section.file { margin:1.25rem 0; border:1px solid var(--border); border-radius:8px; overflow:hidden; }
  section.file > h2 { margin:0; padding:.75rem 1rem; background:color-mix(in srgb, var(--border) 40%, transparent); font-family:var(--mono); font-size:.95rem; }
  table { width:100%; border-collapse:collapse; }
  th, td { text-align:left; padding:.5rem .75rem; border-top:1px solid var(--border); vertical-align:top; }
  th { font-size:.8rem; color:var(--muted); text-transform:uppercase; letter-spacing:.04em; }
  td.loc { font-family:var(--mono); color:var(--muted); font-size:.8rem; white-space:nowrap; }
  td.sev { font-family:var(--mono); font-size:.75rem; font-weight:700; text-transform:uppercase; }
  td.sev.error { color:var(--err); }
  td.sev.warning { color:var(--warn); }
  td.sev.info { color:var(--info); }
  td.rule a { font-family:var(--mono); font-size:.8rem; color:var(--muted); text-decoration:none; border-bottom:1px dotted var(--muted); }
  td.rule a:hover { color:var(--fg); }
  .path { font-family:var(--mono); font-size:.75rem; color:var(--muted); display:block; margin-top:.25rem; }
  .fix { color:var(--ok); margin-top:.25rem; font-size:.85rem; }
  footer { padding:1rem 1.5rem; color:var(--muted); font-size:.8rem; border-top:1px solid var(--border); }
  code { font-family:var(--mono); background:color-mix(in srgb, var(--border) 40%, transparent); padding:1px 4px; border-radius:3px; }
</style></head>
<body>
<header>
  <h1>${esc(title)}</h1>
  <div class="summary">Scanned ${report.files.length} file(s) in ${report.durationMs}ms.</div>
</header>
<main>
${total === 0 ? '<p class="summary">All clean. Nothing to report.</p>' : fileSections}
</main>
<footer>Generated by <a href="https://github.com/MukundaKatta/mcpcheck">mcpcheck</a>.</footer>
</body></html>
`;
}

function renderFileSection(file: string, issues: Issue[]): string {
  const rows = issues.map((i) => {
    const loc = i.line ? `line ${i.line}` : "—";
    const rule = `<a href="https://github.com/MukundaKatta/mcpcheck/blob/main/docs/RULES.md#${esc(i.ruleId)}">${esc(i.ruleId)}</a>`;
    const fix = i.fix ? `<div class="fix">Autofix: ${esc(i.fix.description)}</div>` : "";
    const path = i.jsonPath ? `<span class="path">at ${esc(i.jsonPath)}</span>` : "";
    return `      <tr>
        <td class="loc">${esc(loc)}</td>
        <td class="sev ${esc(i.severity)}">${esc(i.severity)}</td>
        <td class="rule">${rule}</td>
        <td>${esc(i.message)}${path}${fix}</td>
      </tr>`;
  }).join("\n");
  return `  <section class="file">
    <h2>${esc(file)} · ${issues.length} issue(s)</h2>
    <table>
      <thead><tr><th>Line</th><th>Sev</th><th>Rule</th><th>Message</th></tr></thead>
      <tbody>
${rows}
      </tbody>
    </table>
  </section>`;
}

function esc(s: string): string {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
