/**
 * `mcpcheck graph <file...>` — render an MCP config (or several) as a
 * Mermaid diagram. Useful for README docs, architecture reviews, and the
 * "I have 12 servers in my config, what are they all for?" audit.
 *
 * Output format: Mermaid flowchart LR; nodes are clients and servers,
 * edges are labelled with the transport kind. Stdio servers are boxed,
 * url servers are rounded, disabled servers dimmed.
 */

import { parseJsonc } from "./jsonc.js";

export interface GraphEntry {
  file: string;
  source: string;
}

export function formatGraph(entries: GraphEntry[]): string {
  const lines: string[] = [
    "%% Generated by mcpcheck — https://github.com/MukundaKatta/mcpcheck",
    "flowchart LR",
  ];

  const nodeIds = new Map<string, string>();
  const idFor = (label: string): string => {
    let id = nodeIds.get(label);
    if (id) return id;
    id = `n${nodeIds.size}`;
    nodeIds.set(label, id);
    return id;
  };

  for (const entry of entries) {
    let parsed: unknown;
    try {
      parsed = parseJsonc(entry.source);
    } catch {
      continue;
    }
    if (typeof parsed !== "object" || parsed === null) continue;
    const c = parsed as Record<string, unknown>;
    const servers =
      (c.mcpServers ?? c.servers ?? c.context_servers) as
        | Record<string, unknown>
        | undefined;
    if (!servers || typeof servers !== "object" || Array.isArray(servers)) continue;
    const clientId = idFor(entry.file);
    lines.push(`  ${clientId}[["${escapeLabel(entry.file)}"]]`);
    for (const [name, raw] of Object.entries(servers)) {
      if (typeof raw !== "object" || raw === null) continue;
      const s = raw as Record<string, unknown>;
      const cmd = typeof s.command === "string" ? s.command : "";
      const url = typeof s.url === "string" ? s.url : "";
      const disabled = s.disabled === true;
      const serverId = idFor(`${entry.file}::${name}`);
      const shape = url
        ? `${serverId}(["${escapeLabel(name)}"])`
        : `${serverId}["${escapeLabel(name)}"]`;
      lines.push(`  ${shape}`);
      if (disabled) lines.push(`  style ${serverId} opacity:0.35,stroke-dasharray: 3 3`);
      const label = cmd
        ? `stdio · ${shortLabel(cmd, Array.isArray(s.args) ? (s.args as unknown[]).slice(0, 2) : [])}`
        : url
          ? `${typeof s.transport === "string" ? s.transport : "http"} · ${shortUrl(url)}`
          : "unknown";
      lines.push(`  ${clientId} -- "${escapeLabel(label)}" --> ${serverId}`);
    }
  }
  return lines.join("\n") + "\n";
}

function shortLabel(cmd: string, args: unknown[]): string {
  const base = cmd.split(/[/\\]/).pop()!;
  const first = args.find((a) => typeof a === "string" && !a.startsWith("-")) as
    | string
    | undefined;
  return first ? `${base} ${first}` : base;
}

function shortUrl(url: string): string {
  try {
    const u = new URL(url);
    return u.hostname + (u.pathname === "/" ? "" : u.pathname);
  } catch {
    return url;
  }
}

function escapeLabel(s: string): string {
  return s.replace(/"/g, '\\"');
}
